# -*- coding: utf-8 -*-
"""Hackathon_Casestudy_15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ND8hnh2mmM81yE6YkgOkCQbKNujnkTr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df = pd.read_csv("/content/BMW_salesdataset_2010-2024.csv")
df.head()

"""**1) Segment-Wise Demand Analysis**"""

# Total demand per segment
seg_demand = df.groupby("Sales_Classification")["Sales_Volume"].sum().sort_values(ascending=False)
print("Global Demand by Segment:")
print(seg_demand)

# Trend over years
seg_year = df.groupby(["Year","Sales_Classification"])["Sales_Volume"].sum().reset_index()

plt.figure(figsize=(10,5))
for seg in seg_year["Sales_Classification"].unique():
    temp = seg_year[seg_year["Sales_Classification"] == seg]
    plt.plot(temp["Year"], temp["Sales_Volume"], label=seg)

plt.title("Segment-Wise Demand Over Time")
plt.legend()
plt.show()

"""**2) Feature-Based Price Analysis (Simple RF Model)**"""

# Encode categorical features
df_model = df.copy()

cat_cols = ["Region","Fuel_Type","Transmission","Sales_Classification","Color","Model", "Mileage_Category", "Powertrain_Category"]
df_model = pd.get_dummies(df_model, columns=cat_cols, drop_first=True)

X = df_model.drop(["Price_USD"], axis=1)
y = df_model["Price_USD"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestRegressor(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2:", r2_score(y_test, y_pred))

# Feature importance
imp = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
print("\nTop 10 Features Influencing Price:\n")
print(imp.head(10))

imp.head(10).plot(kind="barh", figsize=(8,6))
plt.title("Top Features Influencing Price")
plt.show()

"""**3) Regional Sales Strategy (Growth/Stagnation/Decline)**"""

# Total sales by region
region_sales = df.groupby("Region")["Sales_Volume"].sum().sort_values(ascending=False)
print("Sales by Region:")
print(region_sales)

# Region trend
region_year = df.groupby(["Region","Year"])["Sales_Volume"].sum().reset_index()

plt.figure(figsize=(10,5))
for r in region_year["Region"].unique():
    temp = region_year[region_year["Region"] == r]
    plt.plot(temp["Year"], temp["Sales_Volume"], label=r)

plt.title("Region-Wise Sales Over Time")
plt.legend()
plt.show()

"""**4) Fuel Type Transition Study (EV + Hybrid)**"""

fuel_year = df.groupby(["Year","Fuel_Type"])["Sales_Volume"].sum().reset_index()

plt.figure(figsize=(10,5))
sns.lineplot(data=fuel_year, x="Year", y="Sales_Volume", hue="Fuel_Type")
plt.title("Fuel Type Demand Over Time")
plt.show()

# Region leading EV/Hybrid
ev_region = df[df["Fuel_Type"].isin(["Electric","Hybrid"])] \
                .groupby("Region")["Sales_Volume"].sum().sort_values(ascending=False)

print("Regions Leading EV/Hybrid Adoption:")
print(ev_region)

"""**5) Transmission Preference Insights**"""

# Trend over time
trans_year = df.groupby(["Year","Transmission"])["Sales_Volume"].sum().reset_index()

plt.figure(figsize=(10,5))
sns.lineplot(data=trans_year, x="Year", y="Sales_Volume", hue="Transmission")
plt.title("Transmission Preference Over Time")
plt.show()

# Price relation
plt.figure(figsize=(6,5))
sns.boxplot(data=df, x="Transmission", y="Price_USD")
plt.title("Price vs Transmission")
plt.show()

# Region-wise transmission share
trans_region = df.groupby(["Region","Transmission"])["Sales_Volume"].sum().unstack().fillna(0)
print(trans_region)

"""**6) Simple Predictive Model — Forecast Sales for 2025**"""

# Prepare forecasting dataset
df_f = df.copy()

df_f = pd.get_dummies(df_f, columns=["Region","Fuel_Type","Transmission","Sales_Classification","Model","Color","Mileage_Category", "Powertrain_Category"], drop_first=True)

X = df_f.drop(["Sales_Volume"], axis=1)
y = df_f["Sales_Volume"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_sales = RandomForestRegressor(n_estimators=300, random_state=42)
rf_sales.fit(X_train, y_train)

print("Sales Forecast Model R2:", rf_sales.score(X_test, y_test))

# Build 2025 rows
df_2024 = df[df["Year"] == df["Year"].max()].copy()
df_2025 = df_2024.copy()
df_2025["Year"] = df["Year"].max() + 1

df_2025_encoded = pd.get_dummies(df_2025, columns=["Region","Fuel_Type","Transmission","Sales_Classification","Model","Color","Mileage_Category", "Powertrain_Category"], drop_first=True)
df_2025_encoded = df_2025_encoded.reindex(columns=X_train.columns, fill_value=0)

forecast_2025 = rf_sales.predict(df_2025_encoded)
df_2025["Forecast_2025"] = forecast_2025

print(df_2025[["Region","Sales_Classification","Forecast_2025"]].head())

"""**7) Profitability Recommendation (Simple Revenue = Price × Volume)**"""

df["Revenue"] = df["Price_USD"] * df["Sales_Volume"]

segment_profit = df.groupby("Sales_Classification")["Revenue"].sum().sort_values(ascending=False)

print("Most Profitable Segments:")
print(segment_profit)

segment_profit.plot(kind="bar", figsize=(8,5))
plt.title("Revenue by Segment")
plt.show()